spring:
  jpa:
    database: POSTGRESQL
  datasource:
    platform: postgres
application:
  url: http://blog.johnspade.ru
  title: Записки Джона
  description: "Блог студента-программиста: мысли о жизни, дневниковые записи и заметки о программировании"